### ISSUE TITLE
请问scopslot 返回对象的参数中data是什么格式？

### ISSUE THREAD

**Issue by hellolex** [kitwon/vue2-event-calendar#1]
请问我传的dateData为如下格式：
[
    {
        title : '库存',
        date:'2018-05-02'
    }
 ]
但是在scopslot 返回对象中怎么都无法显示出值，slot-scope="item"
item.data.title 不行
item.data[0].title 也不行
item.data[0]['title'] 也不行

**Comment by kitwon** [comment]
data对象是包含匹配日期的数据数组，item.data[0].title应该是可以，你可以查看下dev/App.vue里面的demo，里面有demo的代码。

**Comment by hellolex** [comment]
查看了下demo，发现按照demo的写法，历遍item.data就能显示：
<div
v-for="(eitem, eindex) in item.data"
:key="eindex">
<span>{{ eitem.title }}</span>
</div>

但是像这样就不行：
<div>{{ item.data[0].title }}</div>

不知道是不是vue我还有些规则没摸明白，总之非常感谢，总算能把数据显示出来了

**Comment by kitwon** [comment]
好的，没其他问题的话我就关闭这个issue了
