### ISSUE TITLE
Wrong date value when firstDay prop is different from 0 

### ISSUE THREAD

**Issue by ghost** [kitwon/vue2-event-calendar#10]
This is a strange bug that happens only on the Month of October, it takes some times to figure it out as on the git demo page everything is fine.

You can check it out at this link https://codesandbox.io/s/jv32nk54ry

In the example the firstDay prop is 1 but the result is wrong for every value that's not 0.

Result

![image](https://user-images.githubusercontent.com/1085151/46348619-d7cc3300-c64f-11e8-8002-d0c9db19b0de.png)

Expected result

![image](https://user-images.githubusercontent.com/1085151/46348691-195cde00-c650-11e8-8b8f-da3d74e73807.png)

**Comment by KristofferBerg** [comment]
Same results here. I just noticed it renders 28th two times :/

![image](https://user-images.githubusercontent.com/4280208/52504592-364e8280-2be9-11e9-8d29-513809940a38.png)

**Comment by KristofferBerg** [comment]
NB: This error occurs even if the firstDay="0":
This is October 2016. Notice the October 30th occur twice:

![image](https://user-images.githubusercontent.com/4280208/52525698-99095200-2cad-11e9-9d32-7a97b7bc26dd.png)

Here's from my project where I output the item.date.day for debugging: 
![image](https://user-images.githubusercontent.com/4280208/52525713-d66ddf80-2cad-11e9-9108-74e4dccb412a.png)

**Comment by kitwon** [comment]
Bug confirmed and it will be fixed next versions, thanks report :)

**Comment by kitwon** [comment]
fixed in v1.0, please upgrade to v1 use `npm install vue2-event-calendar@next -S`

**Comment by KristofferBerg** [comment]
Thanks, but trying this on my project, i get some errors:

![image](https://user-images.githubusercontent.com/4280208/62827700-defb9000-bbd4-11e9-9c71-60702e3ef166.png)

Any ideas on what it could be?

**Comment by kitwon** [comment]
You can include this component path in babel-loader config. If use **vue-cli3**, you can set [transpileDependencies](https://cli.vuejs.org/config/#transpiledependencies) like 
```javascript
```

**Comment by kitwon** [comment]
You can include this component path in babel-loader config. If use **vue-cli3**, you can set [transpileDependencies](https://cli.vuejs.org/config/#transpiledependencies) like
```javascript
module.exports = {
  transpiledependencies: ['node_modules/vue2-event-calendar']
}
```

ESM support will be added in few days.

**Comment by KristofferBerg** [comment]
Great! Thanks a lot! If anyone else is struggling, here's the code that got it working:

`// vue.config.js
module.exports = {
    transpileDependencies: ['vue2-event-calendar']
}
`
