### ISSUE TITLE
Rendering irrelevant week rows in month mode

### ISSUE THREAD

**Issue by KristofferBerg** [kitwon/vue2-event-calendar#11]
Seems like it renders irrelevant week rows in month mode. version 0.4.4
![image](https://user-images.githubusercontent.com/4280208/52505173-fe483f00-2bea-11e9-9bcb-945cd5f23546.png)

NB: The opacity 25% row at the bottom, which is the irrelevant.

**Comment by kitwon** [comment]
Please provide more information on your issue and a _runnable_ minimal reproduction (repo or jsfiddle).

**Comment by KristofferBerg** [comment]
Yeah, sure :) I've forked the codesandbox from @leRenard from #10  and display #00ff00 <- green color on day-items that is "is-otherMonth": https://codesandbox.io/s/zkzq8x383

![image](https://user-images.githubusercontent.com/4280208/52520920-a7d11400-2c6f-11e9-8ee6-8fcfa1b4fb17.png)

The last row has no relevance in the current month, and I guess it's because you've hardcoded the "6 rows" in source code? :) https://github.com/kitwon/vue2-event-calendar/blob/c379c90204fa23efde216fd352f00dd6838038fb/vue2-event-calendar.js#L405

**Comment by kitwon** [comment]
Sorry to reply to you so late.
In some case like March 2019 that has 6 rows. Many calendars app use 6 as default. So, I don't think it is a bug. If you don't need this day, Maybe you can trim it in the template. 😀

**Comment by KristofferBerg** [comment]
No worries. Thanks for checking. Maybe have a property in the future; ex. row-count-lock="6" or something.

**Comment by kitwon** [comment]
Thanks for your advice. I will consider adding it in next ver  :)
