### ISSUE TITLE
Week mode show wrong week if firstDay != 0

### ISSUE THREAD

**Issue by KristofferBerg** [kitwon/vue2-event-calendar#12]
![image](https://user-images.githubusercontent.com/4280208/59563202-f97f1600-9036-11e9-9e4b-f7e5246908cd.png)

Running version 1.0.4. Today is the Sunday june 16 and our week here in Norway dont start on Sunday. It starts tomorrow, Monday 17, so we should be looking at week 24 in the screenshot above.

Here is Google Calendar for comparison: 
![image](https://user-images.githubusercontent.com/4280208/59563365-5ed40680-9039-11e9-9718-95bd00c5b081.png)

**Comment by kitwon** [comment]
Thanks for your report again😊, please upgrade to v1.06.

It seems is a bug when the start day of the month less than `firstDay` of user setting. I just add below code in `startDay` calculating function.

```javascript
if (start.day() < firstDay) {
  // if start day behind of the view's first day,
  // start day should subtract a week -
  // to include all days of current month
  start = start.subtract(1, 'week');
}
```

But I am not sure my function will match any case. If you found any unexpected actions. Report anytime. 🌚
