### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by GHERSOLUTIONS** [kitwon/vue2-event-calendar#13]
OS: Mac
npm: 6.1.0
node: v10.4.1
vue --version: 3.8.4

Getting this error:

Failed to compile.

./node_modules/vue2-event-calendar/src/calendar.vue
Module not found: Error: Can't resolve 'less-loader' in '/Applications/MAMP/htdocs/OpenCabana/opencabana-admin-v2'

**Comment by NicolaeCasir** [comment]
`npm i less less-loader --save`
;)

**Comment by kitwon** [comment]
Yep, add less and less-loader to your project can solve this problem.
Mabey next version will change it to pure CSS. 🧐
