### ISSUE TITLE
When firstDay is not zero, calendar is offseted wrong

### ISSUE THREAD

**Issue by marcosPerezRubio** [kitwon/vue2-event-calendar#14]
Hello!

Thanks for this library, is really helpful.

In my case, when a month starts at Sunday and firstDay is one, the calendar begins to render at Monday 2.

Even the date is correct, the expected behavior should be to display te last week of the previous month.

This is a working example with sunday as a first day of this december 2019. Everything is correct.
![expected_behavior](https://user-images.githubusercontent.com/10812385/69620447-b42b2f80-103d-11ea-9557-4aeb12f05921.png)

The problem happen when I set firstDay as 1:
![wrong_calendar](https://user-images.githubusercontent.com/10812385/69620455-b7262000-103d-11ea-9127-c9d19b0cf15c.png)

Hope this description is helpful,

It's something that can be fixed in short term?

Regards

**Comment by kitwon** [comment]
Thanks report. This problem has been fixed in  ~1.0.
If the latest version also have this problem, Can you provide a live demo?

**Comment by marcosPerezRubio** [comment]
Hello,

Thanks for the update, we were working with an old version.

Sorry for the inconvenience!

**Comment by kitwon** [comment]
Not a problem. Open anytime.
