### ISSUE TITLE
scoped Items don't show on firefox

### ISSUE THREAD

**Issue by ghost** [kitwon/vue2-event-calendar#5]
Tested on FF	60.0.1 on mac and ubuntu

Chrome

![image](https://user-images.githubusercontent.com/1085151/40830146-d63251c6-6585-11e8-8666-40e2b10e54b7.png)

FF

![image](https://user-images.githubusercontent.com/1085151/40830152-ddc3377a-6585-11e8-99d3-f360290d4cac.png)

**Comment by kitwon** [comment]
Bug has been fixed. Thanks for report. 😀

**Comment by ghost** [comment]
No problem! it's a nice calendar 👍.

did you push your commit on git ? Because I would like to update this module 😇

**Comment by kitwon** [comment]
Yep, you can update to 0.4.4
