### ISSUE TITLE
Uncaught reference error when trying on browser

### ISSUE THREAD

**Issue by godguide1** [kitwon/vue2-event-calendar#6]
I am trying to use your beautiful Vuejs event calendar on browser with using the minified  version

     <script src="./vue2-event-calendar.min.js"></script>

      <view-booked-jobs>
		<Calendar startDate="2018-03-07" :dateData="timeslots" :renderHeader="renderHeader" slot="calendar">
						<div slot="header-left">
							<Button>month</Button>
							<Button>week</Button>
						</div>

						<div
							:class="['calendar-item', { 'is-otherMonth': !isCurMonth }]"
							slot-scope="item"
						>
							<div :class="['calendar-item-date']">
								<div>
									<div>
										<span>{{item.timeslots.timeslot}}</span>
									</div>
									<div>
										<ul>
											<li v-for="driver in item.timeslots.driver">{{ driver.name }} {{ driver.runs }} {{ driver.qty }}</li>
										</ul>
									</div>
								</div>
							</div>
							<div class="calendar-item-name">{{item.data.title}}</div>
						</div>
					</Calendar>
				</view-booked-jobs>

view-booked-jobs is my js component and here below; but I need to know your project name to enable me do a local component registration in my Vue instance, for example

    const ViewBookedJobs = {
        template:`
           <div>
                <slot name="calendar"></slot>
           </div>
        `
    };

    new Vue({
        components:{
           //Please what name can I use here for your project to load or be referenced as Calendar?
            'Calendar': Calendar 
            'view-booked-jobs': ViewBookedJobs
        }
    });

**Comment by kitwon** [comment]
I am sorry to deal with this problem so late.
You can download the brach 1.0 and add `vue2-event-calendar.umd.min.js` to your project.
